[master]
k8s-master ansible_host=3.123.30.97
[workers]
k8s-worker-1 ansible_host=63.187.84.81
k8s-worker-2 ansible_host=3.72.92.183

[k8s_cluster:children]
master
workers

[k8s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

